### PR TITLE
Skip file to process when first/CTB is zero

### PR DESCRIPTION
**Pull request by galaxiesFarApart**
It is possible that someone could execute pgpdump against a non-key file which may begin with one or more "zero" bytes. It may also be possible that a legitimate "key file" is being used but its first/CTB byte has been "corrupted" and is now nothing more than "zero". In either case, if the first/CTB byte is "zero", then simply issue message and terminate processing. No need to do anymore work on the file.

Two sample "corrupted" key files and the normal/current pgpdump responses are attached:

[DSA_ELGAMAL_test.raw_prezerobytes.pubkey-pgpdump.zip](https://github.com/kazu-yamamoto/pgpdump/files/14001327/DSA_ELGAMAL_test.raw_prezerobytes.pubkey-pgpdump.zip)

[DSA_ELGAMAL_test.raw_prezerobytes.pubkey-armor-pgpdump.zip](https://github.com/kazu-yamamoto/pgpdump/files/14001328/DSA_ELGAMAL_test.raw_prezerobytes.pubkey-armor-pgpdump.zip)

### CODE REVIEW

**Review by kazu-yamamoto — CHANGES_REQUESTED** [review]
It seems to me that this guard is good.
But the policy of `pgpdump` is that the commit history should be *liner*.
So, please rebase this PR onto `master` with minimal changes.

**Comment by kazu-yamamoto** [comment]
@galaxiesFarApart Gentle ping.

This blocks #39.

**Comment by galaxiesFarApart** [comment]
OK - what do you need for me to do?

**Comment by kazu-yamamoto** [comment]
Again, please rebase your commits onto `master` to show minimum difference to me.

**Comment by galaxiesFarApart** [comment]
I am rather new to git - only started when helping with pgpdump. Other program development  (over many years) has been on stand-alone non-collaborative projects (some later ones have been "published" on SourceForge).

I have a local (home, BSD) git repository which I cloned from my github/pgpdump repository. I made changes to packet.c locally and then pushed that to my githug/pgpdump repository.

So will a "rebase from home BSD repo to my github/pgpdump repo" do what you need, or will something else need to be done? I want to make sure to do the right thing.

**Comment by kazu-yamamoto** [comment]
The current my `master` looks:



While after trying to merge your branch, the tree looks:



I don't want to merge this messy history to my repo.

Github says that the difference is only on `packet.c`.
So, just modify `packet.c` on my `master` and commit it then make a pull request.
If you don't know what `push -f` is, a new PR is also acceptable.

**Pull request closed without merging**
