### PR TITLE
Updated public key algorithms

### PR DESCRIPTION
**Pull request by Hasimir**
* Added EdDSA (pub 22).
* Adjusted ECDSA line to match format for DSA line (i.e. acronym
  followed by full name, followed by "(pub NN)").

### CODE REVIEW

**Comment by Hasimir** [comment]
I've also tested it and it both works and does not run over into a new line in an xterm (or iterm in my case).

**Comment by kazu-yamamoto** [comment]
I'm on vacation. Please wait for a while.

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contribution!

**Comment by Hasimir** [comment]
You're welcome.

**Comment by kazu-yamamoto** [comment]
Released: http://www.mew.org/~kazu/proj/pgpdump/en/

**Comment by Hasimir** [comment]
Although you forgot to bump the copyright year.  😉

**Comment by kazu-yamamoto** [comment]
I heard that it is meaningless to bump the copyright year from the legal point of view.

**Comment by Hasimir** [comment]
I think it may depend on who or what holds the copyright and the legal jurisdiction.  Where the copyright holder is a person, that's probably true because the copyright term is from the first year to the death of the author plus N years; where N is 50 for the Berne Convention or 70 for any country with an FTA with the USA and a few other countries.

For organisations like corporations it's from the year plus some other number of years which can vary, so bumping it might be useful in that case or if the copyright is subsequently transferred to a trust or an estate.

**Pull request merged**
