### PR TITLE
Gf apgpdump

### PR DESCRIPTION
**Pull request by galaxiesFarApart**
upload  modifications to support GnuPG-2.3.3 ECC curves, additional hash and algorithm names

### CODE REVIEW

**Review by kazu-yamamoto — CHANGES_REQUESTED** [review]
Looks excellent!
It would be nice if we had test data for this change in the `data/` directory.

**Comment by galaxiesFarApart** [comment]
Hmmmm - I have actual gpg-2.3.3 keys that I generated to use and review via "hexedit", that use a fictitious "userid", but don't know if valid keys would be best. One key for every key-type minus "smart card" since I don't have one.

For the initial testing, I copied out 20 bytes of an actual key so that I could get a "look" at the first public key data packet, ECC portion.

**Comment by galaxiesFarApart** [comment]
I also have output files for all of the keys tested as well as correlated gpg-2.3.3 "--list-packets" output files.

**Comment by kazu-yamamoto** [comment]
A fictitious id such as alice@example.com is good. But if you hesitate to add such data, I will merge this PR as is.

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contribution!
If you wish, I will release a new version.

**Comment by galaxiesFarApart** [comment]
Yes - go ahead and release it.

**Comment by kazu-yamamoto** [comment]
Version 0.34 has been released.
https://www.mew.org/~kazu/proj/pgpdump/en/

**Pull request merged**
