### PR TITLE
Use Automake, and other build improvements

### PR DESCRIPTION
**Pull request by rhansen**
Several commits (please do not squash) to improve the build experience.  In particular, use Automake to build so that features such as VPATH builds work.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Transition from `.in` to `.ac` is OK.
However, introducing a new script such as `git-version-gen` is not acceptable due to the `xz` incident.

**Comment by rhansen** [comment]
If you trust that [gnulib](https://www.gnu.org/software/gnulib/) hasn't been compromised, you can compare `git-version-gen` with https://git.savannah.gnu.org/cgit/gnulib.git/tree/build-aux/git-version-gen and see that the script is not malicious.  The `git-version-gen` script from gnulib is suggested by the [autoconf documentation for `AC_INIT`](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/autoconf.html#index-AC_005fINIT-2)

**Comment by rhansen** [comment]
FYI, my motivation for opening this pull request is to prepare for a couple of other pull requests I'm working on for the following branches:
  * https://github.com/rhansen/pgpdump/commits/test — improve UX for running the unit tests
  * https://github.com/rhansen/pgpdump/commits/fixes — improve handling of corrupt/bad data

**Comment by rhansen** [comment]
Friendly ping @kazu-yamamoto

**Comment by kazu-yamamoto** [comment]
I was very busy in the last week.
I hope I can take time for several issues including this in this week.

**Comment by kazu-yamamoto** [comment]
Sorry for the delay.

`make dist` creates `pgpdump-0.36.14-f63d.tar.gz`
I guess `f63d` is the first two bytes of HEAD's SHA1.
Where does this version conversion come from?
I would like to have simply `pgpdump-0.36.tar.gz` when releasing.

**Comment by rhansen** [comment]
> Sorry for the delay.

No worries, I just wasn't sure if you had seen my reply.  And now it's my turn to apologize for not seeing your reply until just now. :slightly_smiling_face: 

> Where does this version conversion come from?

The version is generated by `build-aux/git-version-gen`.  That script gets it from running `git describe --abbrev=4 --match="v*" --tags HEAD`.  

> I would like to have simply `pgpdump-0.36.tar.gz` when releasing.

Only non-tagged commits get that `.n-hash` part added to the version string (where `n` is the number of commits since the most recent tag, and `hash` is the abbreviated commit ID of the commit you are building).  You can try building from a commit with a temporary tag to see the effect:

```sh
git tag v0.37
autoreconf -fviW all
./configure
make distcheck
git tag -d v0.37
```

**Comment by kazu-yamamoto** [comment]
OK.
Very clear.
I'm going to merge this PR.

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Pull request merged**
